### ISSUE TITLE
Wrong code sample

### ISSUE THREAD

**Issue by itcai** [openkruise/openkruise.io#86]
Please fix the wrong code sample at [here](https://github.com/openkruise/openkruise.io/blob/master/docs/user-manuals/sidecarset.md#metadata-whitelist) and [here](https://github.com/openkruise/openkruise.io/blob/master/i18n/zh/docusaurus-plugin-content-docs/version-v1.3/user-manuals/sidecarset.md#metadata-%E7%99%BD%E5%90%8D%E5%8D%95)
```yaml
metadata:
  name: kruise-configuration
  namespace: kube-system #this would lead to an unexpected result.
```
The namespace field should be fixed as kruise-system.
